export const DELETE_MOVIES_REQUEST = 'DELETE_MOVIES_REQUEST';
export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS';
export const DELETE_MOVIES_FAILURE = 'DELETE_MOVIES_FAILURE';

export const SORT_MOVIES = 'SORT_MOVIES';
