export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_FAILURE = 'GET_MOVIES_FAILURE';

export const POST_MOVIES_REQUEST = 'POST_MOVIES_REQUEST';
export const POST_MOVIES_SUCCESS = 'POST_MOVIES_SUCCESS';
export const POST_MOVIES_FAILURE = 'POST_MOVIES_FAILURE';

export const DELETE_MOVIES_REQUEST = 'DELETE_MOVIES_REQUEST';
export const DELETE_MOVIES_SUCCESS = 'DELETE_MOVIES_SUCCESS';
export const DELETE_MOVIES_FAILURE = 'DELETE_MOVIES_FAILURE';

export const FILTER_MOVIES = 'FILTER_MOVIES';

export const SORT_MOVIES = 'SORT_MOVIES';
